# Generated by Django 5.0.6 on 2024-07-01 21:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('empresa_nro_ruc', models.CharField(max_length=11, unique=True)),
                ('empresa_razon_social', models.CharField(max_length=150)),
                ('empresa_acronimo', models.CharField(max_length=5)),
                ('empresa_direccion', models.CharField(max_length=150)),
                ('empresa_avatar', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('empresa_estado', models.IntegerField(choices=[(0, 'Sin activar / Nuevo'), (1, 'Activo'), (2, 'Suspendido'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['empresa_id'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('sucursal_nombre', models.CharField(max_length=150)),
                ('sucursal_direccion', models.CharField(max_length=150)),
                ('sucursal_acronimo', models.CharField(max_length=15, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.empresa')),
                ('sucursal_ubigeo', models.ForeignKey(null=1, on_delete=django.db.models.deletion.RESTRICT, to='api.distrito')),
            ],
            options={
                'db_table': 'sucursales',
                'ordering': ['sucursal_id'],
            },
        ),
    ]
